name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      NODE_ENV: test
      DATABASE_URL: file:./test.db
      VITE_API_URL: http://localhost:3000/v1/trpc
      APP_URL: http://localhost:5173
      CI: true

    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4
        with:
          path: frontend

      - name: Checkout Backend Repository
        uses: actions/checkout@v4
        with:
          repository: jragland3/bug-tracker-backend
          path: backend
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun Depencies
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun=${{hashFiles('frontend/bun.lock', 'backend/bun.lock') }}

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
        
      - name: Install browsers
        working-directory: frontend
        run: bunx playwright install --with-deps

      # Backend Setup
      - name: Install Backend Dependencies
        working-directory: backend
        run: bun install

      - name: Prepare Prisma Database
        working-directory: backend
        env:
          DATABASE_URL: file:./test.db
          NODE_ENV: test
        run: |
          echo "DATABASE_URL = $DATABASE_URL"
          bunx prisma migrate reset --force
          sqlite3 $DATABASE_URL ".tables"

      - name: Start backend server
        working-directory: backend
        env:
          DATABASE_URL: file:./test.db
          NODE_ENV: test
        run: |
          bun run start:e2e &
          BACKEND_PID=$!
          echo $BACKEND_PID > backend.pid
          sleep 5
          curl -v http://localhost:3000/health


      # Frontend Setup
      - name: Install Frontend Dependencies 
        working-directory: frontend
        run: bun install
      
      - name: Run Playwright tests
        working-directory: frontend
        run: bunx playwright test --reporter=junit,html
        env:
          DATABASE_URL: file:./test.db
          APP_URL: http://localhost:5173
          VITE_API_URL: http://localhost:3000/v1/trpc
          NODE_ENV: test

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-chromium
          path: ./frontend/playwright-report

      - name: Upload JUnit results for Github
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: ./frontend/results.xml

      - name: Publish test results to Github
        uses: dorny/test-reporter@v2
        with:
          name: Playwright E2E
          path: ./frontend/results.xml
          reporter: junit
